name: ci
on:
  workflow_dispatch:
  workflow_call:
    outputs:
      image-tag:
        description: "image tag"
        value: ${{ jobs.build-and-test.outputs.image-tag }}
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # need this for OIDC
      contents: read
    environment: main
    outputs:
      image-tag: ${{ steps.set-image-tag.outputs.IMAGE_TAG }} 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

         # TODO
      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}
      
      # CloudFormation Lint
      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2
      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          shopt -s globstar # enable globbing
          cfn-lint --version
          cfn-lint -t ./**/*.yaml

     
     
      # CloudFormation Static Analysis
      - name: Cfn Nag
        id: cfn-nag
        uses: stelligent/cfn_nag@master
        with:
          input_path: templates
          #output_path: cfn_nag.sarif

      # Summarize cfn_nag failures and return it as exit code
      - name: Check for cfn_nag scan failures
        id: cfn-nag-check-failure        
        run: |
          exit `grep Failures cfn_nag.out | awk '{ SUM += $3} END { print SUM }'`
          
      # Build docker images
      # Set new image tag
      # Scan new image
      # Generate summary